@Api4_HostAddress = http://localhost:5156

///Cliente
GET {{Api4_HostAddress}}/Cliente
Accept: application/json

### 
PATCH {{Api4_HostAddress}}/Problema/Atualizar
Content-Type: application/json

{
    "id": 1,
    "status": "Entregue",
    "Valor": 10.56
}

###
GET {{Api4_HostAddress}}/Problema/Funcionario
Accept: application/json